name: fmt
description: Money tracker app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  flutter_bloc: ^8.1.1
  form_validator: ^2.1.1
  fl_chart: ^0.61.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  dart_code_metrics: ^5.4.0
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: SF UI Display
      fonts:
        - asset: fonts/sf-ui-display-black-58646a6b80d5a.otf
        - asset: fonts/sf-ui-display-bold-58646a511e3d9.otf
        - asset: fonts/sf-ui-display-heavy-586470160b9e5.otf
        - asset: fonts/sf-ui-display-light-58646b33e0551.otf
        - asset: fonts/sf-ui-display-medium-58646be638f96.otf
        - asset: fonts/sf-ui-display-semibold-58646eddcae92.otf
        - asset: fonts/sf-ui-display-thin-58646e9b26e8b.otf
        - asset: fonts/sf-ui-display-ultralight-58646b19bf205.otf
          style: normal
